// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cqWB_5PXGUeSrTCw8J2p_vlh0HrutY0',
    appId: '1:847934410234:web:ee3c9f852f7cc5af3da843',
    messagingSenderId: '847934410234',
    projectId: 'syncro-1f9a6',
    authDomain: 'syncro-1f9a6.firebaseapp.com',
    storageBucket: 'syncro-1f9a6.appspot.com',
    measurementId: 'G-ZNJ286SY94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHdkR2EQ4X9nwvJhxlCgQ5i8cJOLF1wCY',
    appId: '1:847934410234:android:c1f84cd5df40ab903da843',
    messagingSenderId: '847934410234',
    projectId: 'syncro-1f9a6',
    storageBucket: 'syncro-1f9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sngpUU_bXVuxT1uG_dM4nOnvClvEOSU',
    appId: '1:847934410234:ios:b73e76fc34bd21ea3da843',
    messagingSenderId: '847934410234',
    projectId: 'syncro-1f9a6',
    storageBucket: 'syncro-1f9a6.appspot.com',
    iosBundleId: 'com.example.syncroFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sngpUU_bXVuxT1uG_dM4nOnvClvEOSU',
    appId: '1:847934410234:ios:b73e76fc34bd21ea3da843',
    messagingSenderId: '847934410234',
    projectId: 'syncro-1f9a6',
    storageBucket: 'syncro-1f9a6.appspot.com',
    iosBundleId: 'com.example.syncroFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1cqWB_5PXGUeSrTCw8J2p_vlh0HrutY0',
    appId: '1:847934410234:web:4323c0bd4a08afd33da843',
    messagingSenderId: '847934410234',
    projectId: 'syncro-1f9a6',
    authDomain: 'syncro-1f9a6.firebaseapp.com',
    storageBucket: 'syncro-1f9a6.appspot.com',
    measurementId: 'G-TKJDVH0E63',
  );
}